<!-- Posizionamento
x: parseInt(PosCircle.getX()) + parseInt(Position.getX()), 
y: parseInt(PosCircle.getY()) + parseInt(Position.getY()),

provare a fare un layer che si sovrappone all'immagine e che al mouse up se draggo crea il pallino
-->


<input type="input" id="associated-scheme" name="associated-scheme" value="<?php echo $this->getBASE64JsonPosition();?>" style="display: none"/>
<!--<input type="input" id="dbg" name="" value="" style="width: 200px"/>-->
<div class="grouped-grid" unselectable="on">
    <?php echo $this->getGridHtml() ?>   
</div>
<div class="grouped-canvas" id="grouped-canvas" unselectable="on">
    
</div>

<script>
    
    
    var objJsGrid = new AdminCanvasManagerGrid('<?php echo $this->getJsonPosition();?>', '<?php echo $this->getImage();?>', 'grouped-canvas','<?php echo $this->getSkinUrl('images/delete.png'); ?>');
    Event.observe(window, 'load', function () {
        objJsGrid.DecorateGrid("<?php echo $this->getChild('grouped.grid')->getId() . '_table';?>");
    });
    
//    jQuery(window).load(function() {
//        jQuery('grouped-canvas').AdminCanvasManagerGrid('<?php echo $this->getJsonPosition();?>', '<?php echo $this->getImage();?>', '<?php echo $this->getSkinUrl('images/delete.png'); ?>');
//    })
</script>