
<style>
        .manuals-lists ul {float: left }
        .manuals-lists ul li { clear: both; margin-bottom: 20px  }
        .manuals-lists ul li a { width: 100%; float:left; }
        .manuals-lists ul li>span {float: left; margin-bottom: 10px }
</style>

<?php

$maxNr = $this->getRowNum() + 0;
if ($maxNr == 0):
        $maxNr = 8;
endif;

$collection = Mage::getResourceModel('fileuploader/fileuploader_collection');
$collection->addFieldToFilter('file_status', 1);
$collection->getSelect()
           ->joinLeft(array('_label' => Mage::getSingleton('core/resource')->getTableName('fileuploader/label')),
                      "_label.fileuploader_id = main_table.fileuploader_id and _label.store_id = " . MAge::app()->getStore()->getId())
            ->joinLeft(array('_label_default' => Mage::getSingleton('core/resource')->getTableName('fileuploader/label')),
                      "_label_default.fileuploader_id = main_table.fileuploader_id and _label_default.store_id = 0")
            ->reset(Varien_Db_Select::COLUMNS)                   
            ->columns(array('main_table.fileuploader_id', 
                            'main_table.uploaded_file', 
                            'main_table.file_content', 
                            'main_table.product_ids', 
                            'main_table.file_status', 
                            'main_table.content_disp', 
                            'main_table.sort_order', 
                            'main_table.update_time',
                            "coalesce(coalesce(_label.value,_label_default.value), main_table.title) as title"))
            ->where('lower(_label_default.value) = ?', "manuale")
            ->order('sort_order');

?>

<div class="manuals-lists">
<?php
     $i = 0;
     $ii = 0;
     if ($collection->count() > 0): ?>
        <?php foreach ($collection as $file): ?>
<?php        if ( $ii == 0):?>
    <ul>
<?php        endif; ?>
        <li>
        <?php echo MAge::helper('fileuploader')->getFilesHtml($file->getData('uploaded_file'), $file->getData('title'), $i++,true,$file->getData('content_disp'),true); ?>
        </li>
<?php   if ($ii == $maxNr): ?>
    </ul>
<?php           $ii = 0;
        else:
                $ii++;
        endif;
        ?>
        <?php endforeach;  ?>

<?php endif;?>
</div>